### ISSUE TITLE
Log middleware with whole pattern

### ISSUE THREAD

**Issue by troylelandshields** [goji/goji#35]
I want to be able to log the entire pattern that was matched in a middleware but this doesn't seem easily doable if I am using submuxes.

If I put the middleware on the root mux then I only get the pattern up to the wildcard. If I put the middleware on the submux then I get the pattern after the wildcard.

Ideally I would like to be able to put it on the root mux and get the whole pattern, but I would settle for doing it on each submux as well.

Do you have advice for how to do this? Thanks.

**Comment by zenazn** [comment]
Sorry—this issue seems to have fallen through the cracks.

I haven't found a great way to do this besides adding a middleware to every mux and submux "along the chain" that grabs patterns out of the local context and appends them to a list. I'll be the first to admit this is ugly—it's just one of those things that turned out to be less easy than I thought it would be when I first designed the APIs.

Other solutions include creating custom `Pattern` types (perhaps a vendored copy of `pat`) that opt-in to cooperative "whole pattern"-building.

**Comment by troylelandshields** [comment]
Yeah your solution is basically what we ended up implementing. Mostly wanted to make sure there wasn't an obviously easy way that I was missing. Appreciate the response, thanks.
