### ISSUE TITLE
Could pat.Param not panic when it the interface is nil

### ISSUE THREAD

**Issue by plirr** [goji/goji#56]
It's not easily catchable (or at least I haven't read how). Easier was editing Param to return "" if the context interface was nil. I can submit a push request, but haven't ever written a test, so will have to figure that out first.

**Comment by plirr** [comment]
```
func Param(r *http.Request, name string) string {
	if r.Context().Value(pattern.Variable(name)) != nil {
		return r.Context().Value(pattern.Variable(name)).(string)
	} else {
		return ""
	}
}
```

**Comment by zenazn** [comment]
If you’d like to, you can `recover()` the panic, or write a small helper function that does that. But I’d prefer to keep the current API, because I believe that it’s better for folks to understand what parameters are and aren’t set in each of their routes, and that Goji help folks out when things aren’t as they expect by erroring loudly instead of silently returning an empty value.

**Comment by airylinus** [comment]
@zenazn  Maybe return an error will be better than panic.

fyi :  [Golang wiki: PanicAndRecover](https://github.com/golang/go/wiki/PanicAndRecover)
>  By convention, no explicit panic() should be allowed to cross a package boundary. Indicating error conditions to callers should be done by returning error value.

**Comment by zenazn** [comment]
Yup—I'm aware of that :)

The reason I originally chose to `panic` was because I viewed this case as a "compile time" error of sorts—I can tell from the text of your program if your program will `panic` in this way. It's clear to me now that not everyone feels this way, but it's certainly too late to change this API (which is certainly not to say that I *would* make a different decision today—I'd have to think about that more)
